name: CodeClaw Export (Opt-in)

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  export:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      CODECLAW_PUBLISH_APPROVED: ${{ secrets.CODECLAW_PUBLISH_APPROVED }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Validate required secrets
        run: |
          test -n "$HF_TOKEN"
          test "$CODECLAW_PUBLISH_APPROVED" = "true"
      - name: Install CodeClaw
        run: pip install codeclaw
      - name: Login to Hugging Face
        run: huggingface-cli login --token "$HF_TOKEN"
      - name: Setup source scope and repo
        run: |
          codeclaw config --source both
          codeclaw config --repo "${{ github.repository_owner }}/codeclaw-auto-export"
          codeclaw config --confirm-projects
      - name: Export locally
        run: codeclaw export --no-push --output /tmp/codeclaw_export.jsonl
      - name: Confirm and publish
        run: |
          codeclaw confirm \
            --file /tmp/codeclaw_export.jsonl \
            --skip-full-name-scan \
            --attest-full-name "CI workflow skip: no human full name context available." \
            --attest-sensitive "Automated CI scan completed; maintainers review artifacts before enablement." \
            --attest-manual-scan "Automated CI path used for team-internal workflow validation."
          codeclaw export --publish-attestation "Repository maintainers explicitly approved CI-based publishing."
