name: Bug report
description: Report a reproducible defect
title: "[bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and why it is incorrect.
      placeholder: Clear and concise defect summary.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps and commands.
      placeholder: |
        1. Run `...`
        2. Set config `...`
        3. Observe `...`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / traceback
      description: Paste relevant logs with secrets removed.
      render: shell
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. Windows 11 / Ubuntu 24.04 / macOS 15
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g. 3.12.8
    validations:
      required: true
